RestaurantReviews/RestaurantReviews.Web/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using RestaurantReviews.Lib;

namespace RestaurantReviews.Web.Controllers
{
    public class ReviewController : Controller
    {
        private Library lib;

        public ReviewController(string mode)
        {
            lib = new Library(mode);
        }

        public ReviewController()
        {
            lib = new Library();
        }

        // GET: Review
        public ActionResult Index(int? restId)
        {
            if (restId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.restId = restId;

            Model.Restaurant r = lib.GetRestaurant((int)restId);

            if (r == null)
            {
                return HttpNotFound();
            }

            Model.Review[] revs = lib.GetReviews((int)restId);

            var revModels =
                ModelConverter.Convert(revs,
                ModelConverter.ConvertLite(r));

            return View(revModels);
        }

        // GET: Review/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Model.Review rev;

            try
            {
                rev = lib.GetReview((int)id);
            }
            catch (Exception)
            {
                return View();
            }

            if (rev == null)
            {
                return HttpNotFound();
            }

            Model.Restaurant r = lib.GetRestaurant(rev.Subject);

            if (r == null)
            {
                return HttpNotFound();
            }

            return View(
                ModelConverter.Convert(rev,
                ModelConverter.ConvertLite(r)));
        }

        // GET: Review/Create
        public ActionResult Create(int? restId)
        {
            if (restId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Model.Restaurant r = lib.GetRestaurant((int)restId);

            if (r == null)
            {
                return HttpNotFound();
            }

            TempData["restId"] = restId;

            return View();
        }

        // POST: Review/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Score, Reviewer, Comment")] Models.Review rev)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    rev.SubjectID = (int)TempData["restId"];
                    lib.AddReview(ModelConverter.Convert(rev));

                    return RedirectToAction("Details", "Restaurant", new { id = rev.SubjectID }); 
                }
            }
            catch
            {
                return View();
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Review/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Model.Review rev;

            try
            {
                rev = lib.GetReview((int)id);
            }
            catch (Exception)
            {
                return View();
            }

            if (rev == null)
            {
                return HttpNotFound();
            }

            Model.Restaurant r = lib.GetRestaurant(rev.Subject);

            if (r == null)
            {
                return HttpNotFound();
            }

            TempData["restId"] = rev.Subject;

            return View(
                ModelConverter.Convert(rev,
                ModelConverter.ConvertLite(r)));
        }

        // POST: Review/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Review rev)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    rev.SubjectID = (int)TempData["restId"];
                    bool result = lib.EditReview(ModelConverter.Convert(rev));

                    if (!result)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }

                    return RedirectToAction("Details", new { id = rev.Id }); 
                }
            }
            catch
            {
                return View();
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Review/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Model.Review rev;

            try
            {
                rev = lib.GetReview((int)id);
            }
            catch (Exception)
            {
                return View();
            }

            if (rev == null)
            {
                return HttpNotFound();
            }

            var r = lib.GetRestaurant(rev.Subject);

            if (r == null)
            {
                return HttpNotFound();
            }

            return View(ModelConverter.Convert(rev,
                ModelConverter.ConvertLite(r)));
        }

        // POST: Review/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                Model.Review rev = lib.GetReview((int)id);
                bool result = lib.RemoveReview((int)id);

                if (!result)
                {
                    return HttpNotFound();
                }

                return RedirectToAction("Details", "Restaurant", new { id = rev.Subject});
            }
            catch
            {
                return View();
            }
        }
    }
}

RestaurantReviews/RestaurantReviews.Web/Views/Review/Create.cshtml
@model RestaurantReviews.Web.Models.Review

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Reviewer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reviewer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reviewer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Restaurant")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantReviews/RestaurantReviews.Web/Views/Review/Delete.cshtml
@model RestaurantReviews.Web.Models.Review

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this review?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reviewer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reviewer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Restaurant", new { id = Model.Subject.Id }, null)
        </div>
    }
</div>

RestaurantReviews/RestaurantReviews.Web/Views/Review/Details.cshtml
@model RestaurantReviews.Web.Models.Review

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            Restaurant
            @*@Html.DisplayNameFor(model => model.SubjectName)*@
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reviewer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reviewer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Details", "Restaurant", new { id = Model.Subject.Id }, null)
</p>

RestaurantReviews/RestaurantReviews.Web/Views/Review/Edit.cshtml
@model RestaurantReviews.Web.Models.Review

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Reviewer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reviewer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reviewer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Restaurant", new { id = Model.Subject.Id }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantReviews/RestaurantReviews.Web/Views/Review/Index.cshtml
@model IEnumerable<RestaurantReviews.Web.Models.Review>

<p>
    @Html.ActionLink("Create New Review", "Create", "Review", new { restId = (int)TempData["restId"]}, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reviewer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reviewer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Review", new { id=item.Id }, null) |
            @Html.ActionLink("Details", "Details", "Review", new { id=item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", "Review", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>